export { default as Cart } from "../components/cart";
export { default as NavBar } from "../components/navBar";
export { default as Home } from "../components/home";
export { default as Catalog } from "../components/catalog";
export { default as Login } from "../components/login";
export { default as Register } from "../components/register";
export { default as Profile } from "../components/profile";
export { default as ProfileDetails } from "../components/profile_details";
export { default as Orders } from "../components/orders";
